### PR TITLE
feat: Make secrets data optional

### LINKED ISSUE #55: The module should all secrets to be created without requiring secrets data to be set

### PR DESCRIPTION
**Pull request by ps-occrp**
This PR makes secrets data optional and allows creating secret resource without a version
This fixes #55

### CODE REVIEW

**Comment by ps-occrp** [comment]
@apeabody or @g-awmalik can you please review this?

**Comment by ps-occrp** [comment]
Can this be merged?

**Comment by ps-occrp** [comment]
@apeabody any update here?

**Review by apeabody — APPROVED** [review]
Thanks for the contribution @ps-occrp!

**Pull request merged**
